### ISSUE TITLE
$set on item in nested array does not work

### ISSUE THREAD

**Issue by g----** [vmalloc/mongomock#127]
Hi, I have mongo collection `my_collection` where each item has array with `posts`.
Looks like this:
```python
{
    _id: ObjectId(),
    posts: [
        {
            _id: ObjectId(),
        }, 
        ...
    ]
}
```
If I want to set `post` as `read` like this:
```python
my_collection.update(
    {'_id': <ObjectId>, 'posts._id': <ObjectId>},
    {'$set': {'posts.$.read': datetime.now()}}
)
```
I get following error:
```
Traceback (most recent call last):
  File "mongotest.py", line 16, in <module>
    {'$set': {'posts.$.read': 1}}
  File "/root/.venvs/mongotest/local/lib/python2.7/site-packages/mongomock/collection.py", line 95, in update
    self._update_document_fields(existing_document, v, _set_updater)
  File "/root/.venvs/mongotest/local/lib/python2.7/site-packages/mongomock/collection.py", line 344, in _update_document_fields
    self._update_document_single_field(doc, k, v, updater)
  File "/root/.venvs/mongotest/local/lib/python2.7/site-packages/mongomock/collection.py", line 384, in _update_document_single_field
    doc = doc.setdefault(part, {})
AttributeError: 'list' object has no attribute 'setdefault'
```

I believe that problem is with `posts.$.read`. MongoMock expects number not `$.

Full example:
```python
# Install dependencies:
#     pip install mongomock pymongo

import mongomock
from bson.objectid import ObjectId

my_collection = mongomock.Connection().db.my_collection

post_id = ObjectId()
my_collection.insert({'posts': [{'_id': post_id}]})
item = my_collection.find_one()

my_collection.update(
    {'_id': item['_id'], 'posts._id': post_id},
    {'$set': {'posts.$.read': 1}}
)
```

**Comment by mdomke** [comment]
I think this should be fixed already.

**Comment by vmalloc** [comment]
Closing. If this is indeed still a bug please open a new issue.
